const player = {
	level: 1,
	gold: 0,
	experience: 0,
	summons: 30,
	summonbosscounter: 0,
	summoninterval: 10000,
	bosslevel: 1,

	head: {},
	chest: {},
	leg: {},
	boot: {},
	ring: {},
	talisman: {},
	necklace: {},
	weapon: {},
	wrist: {},
	shoulder: {},
	book: {},
	glove: {},

	totalHealth: 0,
	totalMana: 0,
	totalDodge: 0,
	totalMagicPow: 0,
	totalDamage: 0,
	totalIceDMG: 0,
	totalFireDMG: 0,
	totalStormDMG: 0,
	totalCritical: 0,
	totalBloodDMG: 0,
	totalShadowDMG: 0,
	totalNatureDMG: 0,
	totalHealPow: 0,
	totalLifesteal: 0,

	basicattackcooldown: false,
	iceboltcooldown: false,
	fireboltcooldown: false,
	stormboltcooldown: false,
	shadowboltcooldown: false,
	thornscooldown: false,
	bloodstrikecooldown: false,
	healcooldown: false,
	shieldcooldown: false,
	buffmagiccooldown: false,
	naturehealcooldown: false,
	manarestorecooldown: false,

	icebuffcooldown: false,
	firebuffcooldown: false,
	stormbuffcooldown: false,
	shadowbuffcooldown: false,
	bloodsapcooldown: false,
	healwingscooldown: false,
	helmetcooldown: false,
	attackbuffcooldown: false,
	magebuffcooldown: false,
	lotuscooldown: false,
	magicattackcooldown: false,
	defensehealcooldown: false,

	buffHealth: 0,
	buffMana: 0,
	buffDodge: 0,
	buffMagicPow: 0,
	buffDamage: 0,
	buffIceDMG: 0,
	buffFireDMG: 0,
	buffStormDMG: 0,
	buffBloodDMG: 0,
	buffCritical: 0,
	buffShadowDMG: 0,
	buffNatureDMG: 0,
	buffHealPow: 0,
	buffLifesteal: 0,

	nerfHealth: 0,
	nerfMana: 0,
	nerfDodge: 0,
	nerfMagicPow: 0,
	nerfDamage: 0,
	nerfIceDMG: 0,
	nerfFireDMG: 0,
	nerfStormDMG: 0,
	nerfBloodDMG: 0,
	nerfCritical: 0,
	nerfShadowDMG: 0,
	nerfNatureDMG: 0,
	nerfHealPow: 0,
	nerfLifesteal: 0,
};

export default player;
